import { registerSystemIpc } from "./system";
import { registerPlayerIpc } from "./player";
import { registerConfigIpc } from "./config";
import { registerLibraryIpc } from "./library";
import { registerNowPlayingIpc } from "./nowPlaying";
import { registerWindowIpc } from "./window";
import { registerPluginIpc } from "./plugin";
import { registerHotkeyIpc } from "./hotkey";
import { registerThemeIpc } from "./theme";
import { registerStreamingIpc } from "./streaming";
import { registerCacheIpc } from "./cache";
import { registerDownloadIpc } from "./download";
import { registerExternalApiIpc } from "./externalApi";
import { registerMcpIpc } from "./mcp";
import { registerStatsIpc } from "./stats";
import { registerUpdateIpc } from "./update";
import { registerAiModelIpc } from "./aiModel";
import { registerPlaylistIpc } from "./playlist";
import { registerRecognitionIpc } from "./recognition";
import { registerOpenccIpc } from "./opencc";
import { registerRomanizationIpc } from "./romanization";
import { registerLyricFetchIpc } from "./lyricFetch";

/** 注册所有 IPC 处理 */
export const registerIpcHandlers = (): void => {
  registerSystemIpc();
  registerPlayerIpc();
  registerConfigIpc();
  registerLibraryIpc();
  registerRomanizationIpc();
  registerLyricFetchIpc();
  registerNowPlayingIpc();
  registerWindowIpc();
  registerPluginIpc();
  registerOpenccIpc();
  registerHotkeyIpc();
  registerThemeIpc();
  registerStreamingIpc();
  registerPlaylistIpc();
  registerRecognitionIpc();
  registerCacheIpc();
  registerDownloadIpc();
  registerExternalApiIpc();
  registerMcpIpc();
  registerAiModelIpc();
  registerStatsIpc();
  registerUpdateIpc();
};
